### ISSUE TITLE
Crashes when opening the Downloads tab

### ISSUE THREAD

**Issue by infoscav** [XilinJia/NewPipeX#2]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

2.6.2

### Steps to reproduce the bug

1. Launch app
2. Open "Downloads" from left-side drawer
3. App immediately crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.26.2
* __OS:__ Linux samsung/p3sxxx/p3s:14/UP1A.231005.007/G998BXXU9FWL3:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.NullPointerException
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.kt:101)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14 Samsung OneUI 6.0

### Affected device model

Galaxy S21 Ultra 5G (SM-G998B/DS)

**Comment by XilinJia** [comment]
Thanks for reporting.  Fixed in the coming 0.26.3

**Comment by XilinJia** [comment]
> Thanks for reporting. Fixed in the coming 0.26.3

Download still has problems.  Though not crashing, the downloaded file is not valid.
